{"name": "User enter info in the fields: 1. First Name, 2.Last Name, 3.Email Address, 4. Phone Number, 5. Message, etc.", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"div.c-forms-confirmation-message.c-html\"}\n  (Session info: chrome=80.0.3987.163)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\contact_us_dt_15_feb_2020.py\", line 36, in txt_is_hr\n    context.app.contact_us_page.txt_is_here(text_here)\n  File \"C:\\Everything\\My_docs\\Self_development\\IT\\Testing\\Automation_08_09_2019\\tellus_dt_04_feb_2020\\pages\\contact_us_page.py\", line 67, in txt_is_here\n    self.verify_text(text, *self.TEXT)\n  File \"C:\\Everything\\My_docs\\Self_development\\IT\\Testing\\Automation_08_09_2019\\tellus_dt_04_feb_2020\\pages\\base_page.py\", line 34, in verify_text\n    actual_text = self.driver.find_element(*locator).text\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 976, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1588043837812, "stop": 1588043845229}, {"name": "Then Click on contact us button", "status": "passed", "start": 1588043845229, "stop": 1588043853045}, {"name": "Then First Name Test_name", "status": "passed", "start": 1588043853045, "stop": 1588043857166}, {"name": "Then Last Name Test_last_name", "status": "passed", "start": 1588043857166, "stop": 1588043857287}, {"name": "Then Email Address TestLogin1234!@gmail.com", "status": "passed", "start": 1588043857287, "stop": 1588043857442}, {"name": "Then Phone Number 1 407 435 44 33", "status": "passed", "start": 1588043857442, "stop": 1588043857538}, {"name": "Then Message Test_message", "status": "passed", "start": 1588043857538, "stop": 1588043857618}, {"name": "Then Click on Sumbit button", "status": "passed", "start": 1588043857618, "stop": 1588043865693}, {"name": "Then Verify Thank you! A representative will be in touch. text is here", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"div.c-forms-confirmation-message.c-html\"}\n  (Session info: chrome=80.0.3987.163)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\contact_us_dt_15_feb_2020.py\", line 36, in txt_is_hr\n    context.app.contact_us_page.txt_is_here(text_here)\n  File \"C:\\Everything\\My_docs\\Self_development\\IT\\Testing\\Automation_08_09_2019\\tellus_dt_04_feb_2020\\pages\\contact_us_page.py\", line 67, in txt_is_here\n    self.verify_text(text, *self.TEXT)\n  File \"C:\\Everything\\My_docs\\Self_development\\IT\\Testing\\Automation_08_09_2019\\tellus_dt_04_feb_2020\\pages\\base_page.py\", line 34, in verify_text\n    actual_text = self.driver.find_element(*locator).text\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 976, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1588043865693, "stop": 1588043869713}], "start": 1588043828685, "stop": 1588043871835, "uuid": "4806c045-089e-4444-a6b4-a8f60e4fbca5", "historyId": "0816776f413123d15725a73872b2e79e", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Contact us form"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}